ETFs_Data = [
    {"nombre": "AZ China", "descripcion": "ETF que sigue el rendimiento del mercado chino", "simbolo": "ASHR"},
    {"nombre": "AZ MSCI Taiwan Index FD", "descripcion": "ETF que sigue el rendimiento del mercado de Taiwán", "simbolo": "EWT"},
    {"nombre": "AZ Russell 2000", "descripcion": "ETF que sigue el rendimiento del índice Russell 2000", "simbolo": "IWM"},
    {"nombre": "AZ Brasil", "descripcion": "ETF que sigue el rendimiento del mercado brasileño", "simbolo": "EWZ"},
    {"nombre": "AZ MSCI United Kingdom", "descripcion": "ETF que sigue el rendimiento del mercado del Reino Unido", "simbolo": "EWU"},
    {"nombre": "AZ DJ US Financial Sect", "descripcion": "ETF que sigue el rendimiento del sector financiero de EE.UU.", "simbolo": "IYF"},
    {"nombre": "AZ BRIC", "descripcion": "ETF que sigue el rendimiento de los mercados de Brasil, Rusia, India y China", "simbolo": "BKF"},
    {"nombre": "AZ MSCI South Korea Index", "descripcion": "ETF que sigue el rendimiento del mercado de Corea del Sur", "simbolo": "EWY"},
    {"nombre": "AZ Barclays Aggregate", "descripcion": "ETF que sigue el rendimiento de bonos agregados", "simbolo": "AGG"},
    {"nombre": "AZ Mercados Emergentes", "descripcion": "ETF que sigue el rendimiento de los mercados emergentes", "simbolo": "EEM"},
    {"nombre": "AZ MSCI EMU", "descripcion": "ETF que sigue el rendimiento de la zona euro (EMU)", "simbolo": "EZU"},
    {"nombre": "AZ FTSE/Xinhua China 25", "descripcion": "ETF que sigue el rendimiento de las principales empresas chinas", "simbolo": "FXI"},
    {"nombre": "AZ Oro", "descripcion": "ETF que sigue el rendimiento del oro", "simbolo": "GLD"},
    {"nombre": "AZ LATIXX MEX CETETRAC", "descripcion": "ETF que sigue el rendimiento de cetes en México", "simbolo": "MXX"},
    {"nombre": "AZ QQQ NASDAQ 100", "descripcion": "ETF que sigue el rendimiento del índice NASDAQ 100", "simbolo": "QQQ"},
    {"nombre": "AZ MSCI Asia Ex-Japan", "descripcion": "ETF que sigue el rendimiento del mercado asiático excluyendo Japón", "simbolo": "AAXJ"},
    {"nombre": "AZ LATIXX MEX M10TRAC", "descripcion": "ETF que sigue el rendimiento del índice M10 en México", "simbolo": "M10.MX"},
    {"nombre": "AZ Barclays 1-3 Year TR", "descripcion": "ETF que sigue el rendimiento de bonos a corto plazo", "simbolo": "SHY"},
    {"nombre": "AZ MSCI ACWI Index Fund", "descripcion": "ETF que sigue el rendimiento del índice global ACWI", "simbolo": "ACWI"},
    {"nombre": "AZ LATIXX Mexico M5TRAC", "descripcion": "ETF que sigue el rendimiento del índice M5 en México", "simbolo": "M5TRAC.MX"},
    {"nombre": "AZ Silver Trust", "descripcion": "E
